brew "apache-arrow"
brew "autoconf-archive"
# brew "cutter"
brew "gobject-introspection-1.0"
brew "libevent"
brew "libtool"
brew "mecab"
brew "mecab-ipadic"
brew "msgpack"
brew "openssl"
brew "pcre"
brew "pkg-config"
brew "python"
brew "rapidjson"
