name: CMake
on:
  push:
    paths:
      - '**/*.cmake'
      - '**/*.cmake.in'
      - '**/CMakeLists.txt'
      - '.github/workflows/cmake.yml'
      - 'Brewfile'
      - 'ci/**'
      - 'cmake/**'
      - 'compose.yaml'
      - 'dockerfiles/*'
      - 'include/**/*.h'
      - 'include/**/*.h.in'
      - 'include/**/*.hpp'
      - 'lib/**/*.c'
      - 'lib/**/*.cpp'
      - 'lib/**/*.h'
      - 'lib/**/*.hpp'
      - 'lib/**/*.rb'
      - 'plugins/**/*.c'
      - 'plugins/**/*.cpp'
      - 'plugins/**/*.h'
      - 'plugins/**/*.rb'
      - 'setup.sh'
      - 'src/**/*.c'
      - 'src/**/*.h'
      - 'test/command/**'
      - 'test/command_line/**'
      - 'test/mruby/**'
      - 'vendor/mruby/**'
  pull_request:
    paths:
      - '**/*.cmake'
      - '**/*.cmake.in'
      - '**/CMakeLists.txt'
      - '.github/workflows/cmake.yml'
      - 'Brewfile'
      - 'ci/**'
      - 'cmake/**'
      - 'compose.yaml'
      - 'dockerfiles/*'
      - 'include/**/*.h'
      - 'include/**/*.h.in'
      - 'include/**/*.hpp'
      - 'lib/**/*.c'
      - 'lib/**/*.cpp'
      - 'lib/**/*.h'
      - 'lib/**/*.hpp'
      - 'lib/**/*.rb'
      - 'plugins/**/*.c'
      - 'plugins/**/*.cpp'
      - 'plugins/**/*.h'
      - 'plugins/**/*.rb'
      - 'setup.sh'
      - 'src/**/*.c'
      - 'src/**/*.h'
      - 'test/command/**'
      - 'test/command_line/**'
      - 'test/mruby/**'
      - 'vendor/mruby/**'
  schedule:
    - cron: |
        0 21 * * *
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  ubuntu:
    name: Ubuntu
    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
            apache-arrow-main: yes
#          - cc: gcc
#            cxx: g++
#            apache-arrow-main: yes
#          - cc: gcc
#            cxx: g++
#            mruby: "OFF"
#          - cc: clang
#            cxx: clang++
#          - cc: clang
#            cxx: clang++
#            ubsan: "ON"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      GRN_WITH_MRUBY: ${{ matrix.mruby }}
      GRN_WITH_UBSAN: ${{ matrix.ubsan }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Prepare cache
        run: |
          cache_dir="${PWD}/cache"
          ccache_dir="${cache_dir}/ccache"
          mkdir -p "${ccache_dir}"
          echo "CCACHE_DIR=${ccache_dir}" >> ${GITHUB_ENV}
          if [ "${CC}" = "gcc" ] && \
             [ -z "${{ matrix.apache-arrow-main }}" ] && \
             [ -z "${GRN_WITH_MRUBY}" ]; then
            download_cache_dir="${cache_dir}/language-models"
            mkdir -p "${download_cache_dir}"
            echo "GRN_LANGUAGE_MODEL_DOWNLOAD_CACHE_DIR=${download_cache_dir}" >> ${GITHUB_ENV}
          fi
      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: cache
          key: cmake-ubuntu-${{ matrix.cc }}-${{ matrix.apache-arrow-main }}-${{ matrix.mruby }}-${{ matrix.ubsan }}-ccache-${{ hashFiles('lib/**', 'src/**', 'plugins/**', 'include/**') }}
          restore-keys: cmake-ubuntu-${{ matrix.cc }}-${{ matrix.apache-arrow-main }}-${{ matrix.mruby }}-${{ matrix.ubsan }}-ccache-
      - name: Install common build dependencies
        run: |
          sudo apt update -o="APT::Acquire::Retries=3"
          sudo apt install -y -V -o="APT::Acquire::Retries=3" \
            build-essential \
            ccache \
            cmake \
            libxsimd-dev \
            ninja-build
      - uses: actions/checkout@v6
        if: matrix.apache-arrow-main == 'yes'
        with:
          path: apache-arrow
          repository: apache/arrow
      - name: Configure Apache Arrow
        if: matrix.apache-arrow-main == 'yes'
        run: |
          ccache --show-stats --verbose --version
          cmake \
            -B apache-arrow/cpp.build \
            -S apache-arrow/cpp \
            --preset ninja-debug-minimal \
            -DARROW_COMPUTE=ON \
            -DCMAKE_INSTALL_PREFIX=$PWD/install
      - name: Build Apache Arrow
        if: matrix.apache-arrow-main == 'yes'
        run: |
          cmake --build apache-arrow/cpp.build
          ccache --show-stats --verbose
      - name: Install Apache Arrow
        if: matrix.apache-arrow-main == 'yes'
        run: |
          cmake --install apache-arrow/cpp.build
      - name: Set environment variables
        run: |
          echo "LD_LIBRARY_PATH=${PWD}/install/lib" >> ${GITHUB_ENV}
          echo "PKG_CONFIG_PATH=${PWD}/install/lib/pkgconfig" >> ${GITHUB_ENV}
      - name: Enable Apache Arrow repository
        if: matrix.apache-arrow-main != 'yes'
        run: |
          sudo apt update -o="APT::Acquire::Retries=3"
          sudo apt install -y -V -o="APT::Acquire::Retries=3" \
            lsb-release \
            wget
          # Always use RC version to detect Apache Arrow related
          # problems as fast as possible. Released Apache Arrow is
          # tested in package related jobs.
          wget https://packages.apache.org/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')-rc/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo sed \
            -i"" \
            -e "s,^URIs: \\(.*\\)/,URIs: \\1-rc/,g" \
            /etc/apt/sources.list.d/apache-arrow.sources
      - name: Install Apache Arrow packages
        if: matrix.apache-arrow-main != 'yes'
        run: |
          sudo apt update -o="APT::Acquire::Retries=3"
          sudo apt install -y -V -o="APT::Acquire::Retries=3" \
            libarrow-compute-dev \
            libarrow-dev \
      - name: Install Groonga build dependencies
        run: |
          sudo apt update -o="APT::Acquire::Retries=3"
          # Use libfaiss-dev instead of libblas-dev, liblapack-dev and
          # libmop-dev once Ubuntu 26.04 is released.
          sudo apt install -y -V -o="APT::Acquire::Retries=3" \
            gdb \
            gettext \
            libblas-dev \
            libedit-dev \
            libevent-dev \
            liblapack-dev \
            libluajit-5.1-dev \
            liblz4-dev \
            libmecab-dev \
            libmsgpack-dev \
            libomp-$(clang --version | grep -o '[0-9]*' | head -1)-dev \
            libsimdjson-dev \
            libstemmer-dev \
            libxxhash-dev \
            libzstd-dev \
            mecab-naist-jdic \
            rapidjson-dev \
            ruby-dev \
            zlib1g-dev
      - name: CMake
        run: |
          ccache --show-stats --verbose --version
          cmake \
            -B ../groonga.build \
            -S . \
            -GNinja \
            -DCMAKE_INSTALL_PREFIX=$PWD/install \
            -DCMAKE_BUILD_TYPE=Debug \
            -DGRN_ALLOW_WARNING=OFF \
            -DGRN_WITH_APACHE_ARROW=ON \
            -DGRN_WITH_BLOSC=auto \
            -DGRN_WITH_MRUBY=${GRN_WITH_MRUBY:-ON} \
            -DGRN_WITH_UBSAN=${GRN_WITH_UBSAN:-OFF}
      - name: Build
        run: |
          ninja -C ../groonga.build
          ccache --show-stats --verbose --version
      - name: Install
        run: |
          ninja -C ../groonga.build install
      - name: Set test environment variables
        run: |
          echo "COLUMNS=79" >> ${GITHUB_ENV}
          echo "TZ=Asia/Tokyo" >> ${GITHUB_ENV}
          if [ "${{ matrix.cc }}" == "gcc" -a \
               "${{ matrix.mruby }}" == "" ]; then
            echo "GRN_TEST_RUN_ALL=yes" >> ${GITHUB_ENV}
          fi
          if [ -e "install/bin/grndb" ] ; then
            echo "GRN_TEST_RUN_COMMAND_LINE=yes" >> ${GITHUB_ENV}
          fi

          echo "${PWD}/install/bin" >> ${GITHUB_PATH}
      - name: Install test dependencies
        run: |
          sudo gem install rubygems-requirements-system
          sudo --preserve-env env MAKEFLAGS=-j$(nproc) gem install \
            grntest \
            pkg-config \
            red-arrow \
            rroonga
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/red-datasets
          key: red-datasets-ubuntu
      - name: "Test: stdio"
        continue-on-error: ${{ matrix.ubsan == 'ON' }}
        run: |
          grntest \
            --base-dir test/command \
            --n-retries=2 \
            --read-timeout=30 \
            --reporter=mark \
            test/command/suite
