name: Release to Launchpad
on:
  push:
#    paths:
#      - '.github/workflows/release-launchpad.yml'
#      - 'doc/source/news/*'
#    tags:
#      - "*"
  pull_request:
#    paths:
#      - '.github/workflows/release-launchpad.yml'
#      - 'doc/source/news/*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Download source archive
        timeout-minutes: 60
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          workflows=(package.yml)
          for workflow in "${workflows[@]}"; do
            run_id=""
            while true; do
              echo "Waiting for run to start ${workflow}..."
              run_id=$(gh run list \
                         --branch ${GITHUB_REF_NAME} \
                         --jq '.[].databaseId' \
                         --json databaseId \
                         --limit 1 \
                         --workflow ${workflow})
              if [ -n "${run_id}" ]; then
                break
              fi
              sleep 300
            done
            gh run watch \
              --exit-status \
              --interval 300 \
              ${run_id}
            gh run download ${run_id} \
              --dir release-artifacts \
              --pattern "release-source.zip"
          done
          unzip release-artifacts/release-source.zip
      - name: Prepare for Launchpad publishing
        if: |
          github.ref_type == 'tag'
        run: |
          cp release-artifacts/release-source/groonga-*.tar.gz ./
          sudo apt update
          sudo apt install -y \
            build-essential \
            debhelper \
            devscripts
      - uses: actions/checkout@v6
        if: |
          github.ref_type == 'tag'
        with:
          path: apache-arrow
          repository: apache/arrow
      - name: Publish to Launchpad
        if: |
          github.ref_type == 'tag'
        env:
          APACHE_ARROW_REPOSITORY: ${{ github.workspace }}/apache-arrow
          LAUNCHPAD_DEPLOY_KEY: ${{ secrets.LAUNCHPAD_DEPLOY_KEY }}
          LAUNCHPAD_UPLOADER_PGP_KEY: "0x32862FBCD63D72C152EFF3A9BD481CAA9168EA87"
        run: |
          echo "${LAUNCHPAD_DEPLOY_KEY}" | gpg --import
          echo "trusted-key ${LAUNCHPAD_UPLOADER_PGP_KEY}" > ~/.gnupg/gpg.conf
#          rake -C packages ubuntu
